
name: travel_planning # for project name <written by czar>

services: 
  frontend:
    container_name: frontend
    build: ../../frontend/
    env_file:
      - .env
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    networks:
      - saas
    volumes:
      - ../../frontend/:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$PORT_FRONT/"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart : on-failure
  auth:
    build: ./backend-services/auth/
    container_name: auth
    networks:
      - saas
    volumes:
      - shared_resources:/data
    depends_on:
      database:
        condition: service_started
      vault:
        condition: service_healthy
    restart: on-failure
  amq:
    image : rabbitmq:3.8-management
    mem_limit: 300m
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 8081:15672
  database:
    container_name: prisma
    build: backend-services/prisma/
    ports:
      - 5555:5555
    replicates: 2
    env_file:
      - .env
    volumes:
     - data:/data
     - shared_resources:/token
     - logs:/var/logs
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - saas
    restart: on-failure
  # security services:

  #logger
  logger:
    build : backend-services/logbull
    restart: on-failure
    container_name: logbull
    volumes:
      - logs:/app/logs
      - shared_resources:/app/:ro
    networks:
      - saas
  ######################
  swagger:
    image: swaggerapi/swagger-ui:v5.31.0
    container_name: swagger
    environment:
      - SWAGGER_JSON=/app/swagger.json
    ports:
     - 8080:8080
    volumes:
      - ./data/:/app/
  #############################
  vault:
    container_name: vault-hashicorp
    build: backend-services/security/hashicorp-vault/
    env_file:
      - .env
    volumes:
      - shared_resources:/shared
      - ./backend-services/security/hashicorp-vault/tools:/tools:rx
    networks:
      - saas
    healthcheck:
      test: ["CMD","curl", "http://0.0.0.0:$PORT_VAULT/", "--silent", "--output", "/dev/null"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart : unless-stopped
  # webserver:
  #   container_name: webserver
  #   build: backend-services/security/modsecurity/
  #   ports:
  #    - "8080:80" #shoud be changed to 443
  #   retries: on-failure
networks:
  saas :
    driver : bridge
volumes:
  data : {}
  logs: {}
  shared_resources:
    driver_opts:
      type : tmpfs
      device : tmpfs
