
name: travel_planning # for project name <written by czar>

services: 
  frontend:
    container_name: frontend
    build: ../../frontend/
    env_file:
      - .env
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    networks:
      - saas
    volumes:
      - ../../frontend/:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$PORT_FRONT/"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart : on-failure
  auth:
    build: ./backend-services/auth/
    container_name: auth
    networks:
      - saas
    volumes:
      - shared_resources:/data
    depends_on:
      database:
        condition: service_started
      vault:
        condition: service_healthy
    restart: on-failure
  amq:
    image : rabbitmq:3.8-management
    mem_limit: 300m
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 8081:15672
  database:
    container_name: prisma
    build: backend-services/prisma/
    ports:
      - 5555:5555
    env_file:
      - .env
    volumes:
     - data:/data
     - shared_resources:/token
     - logs:/var/logs
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - saas
    restart: on-failure
  # security services:

  #elk stack
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m" 
    networks:
      - saas
  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    healthcheck:
        test: ["CMD-SHELL", "curl -sf http://localhost:5601/api/status || exit 1"]
        interval: 60s
        timeout: 1m
        retries: 3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - NODE_OPTIONS="--max-old-space-size=4096"
      - TELEMETRY_ENABLED=false 
      - XPACK_SECURITY_ENABLED=false
      - XPACK_SECURITY_AUDIT_ENABLED=false
    networks:
      - saas
    depends_on:
      - elasticsearch
    restart: on-failure
  logstash :
    image : logstash:8.12.0
    container_name: logstash
    user : root
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - logs:/var/log/postgresql
      - ./data/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
    depends_on:
      - elasticsearch
    networks:
      - saas
    restart: on-failure
  swagger:
    image: swaggerapi/swagger-ui:v5.31.0
    container_name: swagger
    environment:
      - SWAGGER_JSON=/app/swagger.json
    ports:
     - 8080:8080
    volumes:
      - ./data/:/app/
  #############################
  vault:
    container_name: vault-hashicorp
    build: backend-services/security/hashicorp-vault/
    env_file:
      - .env
    volumes:
      - shared_resources:/shared
      - ./backend-services/security/hashicorp-vault/tools:/tools:rx
    networks:
      - saas
    healthcheck:
      test: ["CMD","curl", "http://0.0.0.0:$PORT_VAULT/", "--silent", "--output", "/dev/null"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart : unless-stopped
  # webserver:
  #   container_name: webserver
  #   build: backend-services/security/modsecurity/
  #   ports:
  #    - "8080:80" #shoud be changed to 443
  #   retries: on-failure
networks:
  saas :
    driver : bridge
volumes:
  data : {}
  logs: {}
  shared_resources:
    driver_opts:
      type : tmpfs
      device : tmpfs
