services:
  dev-db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - rihla

volumes:
  postgres_data:

networks:
  rihla:

